A fundamental task in thermal engineering is the transfer of heat between two flowing fluid streams. This function is typically accomplished using a heat exchanger, a device widely used in applications such as air-conditioning systems, chemical processing, automotive radiators, and power generation. Heat exchange is driven by the temperature difference between the two streams. Most conventional heat exchangers employ metallic walls to separate the fluids, as metals offer high thermal conductivity and structural strength, making them suitable for high-temperature and high-pressure applications @HEMetal.

Heat exchangers may operate between two liquids, a liquid and a gas, or two gas streams. There are three main types of heat exchangers, denoted by the flow direction of the working fluids @HeatTransferText. The particular type of heat exchanger utilized in this project is referred to as a counterflow heat exchanger with water and air as the working fluids @MPHXArticle. In a counterflow configuration, the hot and cold fluids enter from opposite ends and flow in opposite directions. This arrangement maintains a more consistent temperature difference along the length of the exchanger, making it the most thermally effective configuration @HeatTransferText.

	Heat exchangers are expensive devices due to the materials used in their construction. However, in many cases, they are operated in conditions that do not require robust properties of metal because there are lower pressures and temperatures @Vinod. These cases would typically be found in air-conditioning and heating operations, where the temperatures are near ambient @HeatTransferText. In these cases, lower-cost materials can be used without significantly sacrificing performance @MPHXArticle. This project investigates the use of thermoplastics as a replacement for metal in a water-to-air heat exchanger @Vinod. Although thermoplastics have a much higher thermal resistance than metals, this does not significantly impede performance @HeatTransferText. The heat exchanger considered for this project is a water-to-air heat exchanger, and the thermal resistance of the air is the limiting factor of performance, not the material properties @tjoenReviewPolymerHeat2009. 

	The heat exchanger considered in this project consists of stacks of identical modules. Each unit is constructed from an injection-molded Microchannel Polymer Heat Exchanger (MPHX) plate made of ABS plastic and a thin polycarbonate film (lamina) bonded to one side of the plate. The film seals internal channels allowing water to flow through the module. Multiple modules are stacked and bonded together, forming continuous water passages and air gaps between plates that permit airflow through the exchanger @ValentinaThesis.

 == The Task

The primary task of this project is to identify suitable materials and assembly methods for bonding the heat exchanger units. Specifically, the project focuses on selecting an appropriate adhesive and/or solvent and defining a reliable application process that satisfies the following design constraints:

- The adhesive must not significantly clog or obstruct water flow passages.
- The adhesive must be compatible with the ABS MPHX plates and PC film.
- A method must be developed to maintain plate flatness during adhesive application and curing, accounting for manufacturing-induced warpage.
- Adhesive application must be semi-automated and predictable for manufacturing scalability.
- A clamping method must be implemented to ensure proper bonding during curing.
- The bonded assembly must withstand internal water pressures of at least 10 psig without leakage.
- The adhesive and bonded joints must tolerate repeated temperature and pressure cycling over the expected service life of the product.